name: GitHub Actions
run-name:  continuous integration and delivery to pre-produbtion env 
on: [push]
jobs:
  Build-Test-Publish:
    runs-on: ubuntu-20.04 
    steps:
      - run: echo "the run numbber in ${{ github.run_numbere }}."
      - run: echo "ğŸ This job's status is ${{ job.status }}."

  Update-Push: 
    needs: Build-Test-Publish
    runs-on: ubuntu-20.04 
    steps:
      - run: docker ps
      - run: echo "update yaml file"
      - run: echo "push to pre-prod repository"